-- CreateTable
CREATE TABLE "Heizungsplakette" (
    "id" TEXT NOT NULL,
    "datenschutzUndNutzungsbedingungen" BOOLEAN NOT NULL,
    "einwilligungDatenverarbeitung" BOOLEAN NOT NULL,
    "aufforderungSofortigeTaetigkeit" BOOLEAN NOT NULL,
    "email" TEXT NOT NULL,
    "artDerImmobilie" TEXT NOT NULL,
    "artDerImmobilieSonstige" TEXT,
    "heizungsart" TEXT NOT NULL,
    "heizungsartSonstige" TEXT,
    "strasse" TEXT NOT NULL,
    "hausnummer" TEXT NOT NULL,
    "postleitzahl" TEXT NOT NULL,
    "ort" TEXT NOT NULL,
    "heizsystem" TEXT NOT NULL,
    "heizsystemSonstige" TEXT,
    "heizungshersteller" TEXT NOT NULL,
    "baujahr" INTEGER NOT NULL,
    "typenbezeichnung" TEXT NOT NULL,
    "typenbezeichnungUnbekannt" BOOLEAN NOT NULL,
    "heizungstechnik" TEXT NOT NULL,
    "heizungstechnikSonstige" TEXT,
    "energietraeger" TEXT NOT NULL,
    "energietraegerSonstige" TEXT,
    "energieausweis" TEXT NOT NULL,
    "energieausweisDate" TEXT,
    "vorname" TEXT NOT NULL,
    "nachname" TEXT NOT NULL,
    "personStrasse" TEXT NOT NULL,
    "personHausnummer" TEXT NOT NULL,
    "personPostleitzahl" TEXT NOT NULL,
    "personOrt" TEXT NOT NULL,
    "istEigentuemer" TEXT NOT NULL,
    "heizungsanlageFotos" TEXT[],
    "heizungsetiketteFotos" TEXT[],
    "heizungslabelFotos" TEXT[],
    "bedienungsanleitungFotos" TEXT[],
    "verzichtAufHeizungsanlageFotos" BOOLEAN NOT NULL,
    "verzichtAufHeizungsetiketteFotos" BOOLEAN NOT NULL,
    "verzichtAufHeizungslabelFotos" BOOLEAN NOT NULL,
    "verzichtAufBedienungsanleitungFotos" BOOLEAN NOT NULL,
    "confirmAccuracy" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Heizungsplakette_pkey" PRIMARY KEY ("id")
);
